language: python # Set the build language to Python

python: 3.6 # Set the version of Python to use

branches: master # Set the branch to build from

install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda

  # Useful for debugging any issues with conda
  - conda info -a

  # Replace dep1 dep2 ... with your dependencies
  - conda env create --file environment.yml
  - conda activate lab-guide

script: true # Skip script (Don't use this if one already exists)

before_deploy:
  - mkdocs build --verbose --clean --strict # Build a local version of the docs

deploy: # Deploy documentation to Github in the gh_pages branch
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: _site
  on:
    branch: master

env:
  global:
    - secure: OiIFYZ6y0X1xLiskzvhWYr/0WXgCpfFH7VpHMsZWioLF774yDxEx9QXOxqsMj4VN4sVVeOF4IjeFr1ucYXOQGyC/Nuq8CR4OM3j41r9ZNpKnSNx5D1hrntJ+orgaeG+9+EymLpMJ4MBTXWyP5fz8YjnG6y9tzyhKagXyLqjBJQA859WRqrqUbN6tl5dcE/L1RyVuNigG9sZ/YnEB2quUsazIMOX0aQJgc5/GgvaT9x3GYzeEJfDSfiJ8noO4NG5mUVVwNuegNUftyxsVbobtrCRXPmo9XcQnx+xDOtNiuiohkdRNuNDLBUsFNZFEQcPQw2ao4Wi55wg3Okl9Mqyhl5TzhLmG1z61vgDFEZPSQ6i53VELDBzWymwiWKZGr4FLwCoLvxFNBr/LB3EROFHl0kiet56QKhPKKbZfx8nuQpfdj6jyV0wviKJ0b/UMNswmp5VRWIpRfHNTzF3TJb85J8h8Bti0XGN2otdOZM7JtLeiu+s90HmljM8Uwweusmdn/Pm5CpLwLEQ7BrnEWhfIx+3WfIDqEOFqH2Q9rV6fEQuI42gJHYYLYgEY2cFR6G5dtd/7ZXk2DUXD1Im4aBhGOjj5/cZhHTI+fA34eGUMRfPBdW04XQNbZQTSfGpspuWAG2nNWxlfnzEt/Se+w8erLQny3XGUk9V+3Pj707rqL3g=
    - secure: Hgf8/yAtJaYcO5V+284/XXPIaNOrgPMS0KyQhhaePV5qoouPdrz4WAb6sRTWVJPBydOKxnp7k4biJrVFTDvXmCF4wa8wUFwyUqZyCRjSZarq/7BQQD74eP7JOwIPcGBGpllQydEVnsni89iQ1BusCyeXDz/fpQvYxKBOg9LV8PlciEtEkbdPUD/TojZIsQds3qCFUwQ8cwgIw/VbWx9vCoDlDD1Bj3pzgR5VhJ28Vu53bHiL74KvLJQHvN84eM3Iqg91rFW4DimAg9fFRuA9sxk/1MiSoTOisNQX0tpi4KlMfn1OgwCXFlxdJ4tgZyNIDHv9HLk93RjlwCP1OyDfYUcUew/QHox3kVf7k4JTiUf8GzzYv8DKlcnVD5SW/hvGeW/dD0yGB8E8lQzZvVB7qyUbH3LwrX5YgAh/2Xazk/ZQJvL0Q0kwnjvAWh2/IIUV1BzWxeLATRKwfTsnrriGbMVRomYjyJ4DBxizGOUpmZksTPS5M3PJ7GYgaUs83sZCWDE8mA72DQT5CAZ1EllZxJTn6ZYzpF9NqP0fMrSEDZMgRpTi6VSBQ02XCoV1udeHLc6POog4/8n/GtSL6qA4kAF/RY07A4w+LUtP2HxKFQdjm9E0Bkp9WDuZ80UuRwR7oKRqdcmfL/3jGHJeFULloxGvBcrAOsYlvZVZZo9G4nQ=
    - secure: UErkYrXhWGZWq87vKwPM6BVgEb869azlOZNM8mmX1WKmF8y4tOrqZUJFGaXENL9/YFf9s/RCCVRnHzNG4ipU0CPkaWo2Kf3VrNWb44backzjfU6Qe+Wkcw+joagumnOWy4W8JGcYLPNIDPRBZs8yrcD2M26olr7SabpLJfL0shA5lYSzdT4hI09EnPMWitz/h9wReFnltGBhMN72mWApZ/SECZrwaS6hBqi3vOCfmkN12YrKRv0/rbfOvtINs0WrmXu+zD0FtWcsysm/+EG76T7otDCY0V2lGMDaMQLyBuvAQAjSwlQiuZFFX35kJT3MkatvYFjOXUrZP9Wg68sdPKmWm5b4lMEHT4LTP9ybgLTZu7IGZZp8kEn9/qVL91kRfAkTadJDJBYc6m0OqdMdI54nrb5Ao0NS9pbfSwHsA0NxdZxL+KINM+ddrrqLR9hn5DrULhlM1QhquckiKApQpKG5hEmgEP+bZeGXsduJgrHZ2DMlGPEq5diogmMOVZ0UJSvPu+iW+sgdw7FaJ9sU9sqhprhROLblULgCgybAXJrCFap4wzaUnyjq7lw2vSznPBfEHQIiZ+Chf+WHPVPS0l4WzE+p4sReP/FY0oYetHzwmVHn5QCSsdQTC+tRuFrW0BQCeOO6yJmHGYHzBI97SvvYkWOFbNJd4aDuJ5GWCRU=
