project:
  type: website
  preview:
    port: 4400

website:
  page-navigation: true
  title: "Lab Guide"
  description: "Lab guide and expectations for the Doss-Gollin Lab in the Civil and Environmental Engineering Department at Rice University"
  site-url: https://dossgollin-lab.github.io/lab-guide
  repo-url: https://www.github.com/dossgollin-lab/lab-guide
  repo-actions: [issue]
  open-graph: true
  
  navbar:
    title: "Doss-Gollin Group Lab Guide"
    search: true
    right: 
      - icon: github
        href: https://www.github.com/dossgollin-lab/lab-guide
      - icon: house-door
        href: https://dossgollin-lab.github.io

  sidebar:
    style: "docked"
    pinned: true
    search: true
    contents:
      - text: Home
        href: index.qmd
      - section: "Lab Expectations"
        contents:
          - text: "Responsibilities"
            href: pages/expectations.qmd
          - text: Well-being
            href: pages/health.qmd
          - text: Harassment and Discrimination
            href: pages/harassment.qmd

      - section: "Lab Resources"
        contents:
          - text: "Authorship"
            href: pages/authorship.qmd
          - text: Contribute to the Lab Guide
            href: pages/contribute.qmd
          - text: Open Science
            href: pages/open-science.qmd
          - text: Traveling
            href: pages/travel.qmd
            
      - section: "Join Us"
        contents:
          - text: "Graduate Admissions"
            href: pages/gradadmissions.qmd
          - text: "Undergraduate Reserach"
            href: pages/undergrad.qmd
          - text: "Onboarding checklist"
            href: pages/checklist.qmd

format:
  html:
    theme: [sandstone, _assets/theme/theme-rice.scss]
    toc: true
    toc-depth: 3
    date-format: long
  pdf:
    documentclass: scrreport

# references
bibliography: _bibliography/library.bib
csl: _assets/references/american-geophysical-union.csl