project:
  type: website
  preview:
    port: 4400

website:
  page-navigation: true
  title: "Lab Guide"
  description: "Lab guide and expectations for the Doss-Gollin Lab in the Civil and Environmental Engineering Department at Rice University"
  site-url: https://dossgollin-lab.github.io/lab-guide
  repo-url: https://www.github.com/dossgollin-lab/lab-guide
  repo-actions: [issue]
  open-graph: true
  
  navbar:
    title: "Doss-Gollin Group Lab Guide"
    search: true
    right: 
      - icon: github
        href: https://www.github.com/dossgollin-lab/lab-guide
      - icon: house-door
        href: https://dossgollin-lab.github.io

  sidebar:
    style: "docked"
    pinned: true
    search: true
    contents:

      - text: Home
        href: index.qmd

      - text: Lab How-To Guides
        href: guides.qmd

      - section: Expectations
        contents:
          - text: Harassment
            href: expectations/harassment.qmd
          - text: Core Expectations
            href: expectations/expectations.qmd
            
      - section: Join Us
        contents:
          - text: Graduate Admissions
            href: joinus/gradadmissions.qmd
          - text: Undergraduate Reserach
            href: joinus/undergrad.qmd

format:
  html:
    theme: [sandstone, _assets/theme/theme-rice.scss]
    toc: true
    toc-depth: 3
    date-format: long
  pdf:
    documentclass: scrreport
