name: lab-guide
channels:
    - conda-forge
    - defaults
dependencies:
    - python >= 3.7
    - mkdocs==1.1
    - pip
    - weasyprint
    - pip:
          - mike==0.4.2
          - mkdocs-material==4.6.3
          - mkdocs-git-revision-date-localized-plugin
          - mkdocs-awesome-pages-plugin
          - mkdocs-pdf-export-plugin
          - mkdocs-material-extensions
