site_name: Doss-Gollin Group Lab Guide
repo_url: https://github.com/jdossgollin/dry-guide
theme: "material"

nav:
    - Home: index.md
    - Code of Conduct: conduct.md
    - Tools:
        - bash: bash.md
        - git and GitHub: git.md
        - Text Editor: editor.md
        - LaTeX: latex.md
        - Reference Manager: zotero.md
    - How To:
        - Manage the Group Website: labsite.md
        - Write a Paper: paper.md
    - Additional Resources: resources.md

markdown_extensions:
    - admonition
    - attr_list
    - codehilite
    - footnotes
    - meta
    - smarty
    - toc:
        permalink: True