theme:
  name: material
  font:
    text: Open Sans
    code: Fira Code
  icon:
    logo: material/account-group-outline
    repo: fontawesome/brands/github

# if there are broken links, throw an error
strict: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/dossgollin-lab
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/jdossgollin
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/jamesdossgollin

site_name: Doss-Gollin Group Lab Guide
repo_name: dossgollin-lab/lab-guide
repo_url: https://github.com/dossgollin-lab/lab-guide
site_url: https://dossgollin-lab.github.io/lab-guide/

markdown_extensions:
  - admonition
  - codehilite:
      linenums: true
  - footnotes
  - attr_list
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - search # necessary for search to work
  - awesome-pages
  - git-revision-date-localized:
      type: date
