site_name: Doss-Gollin Group Dry Guide
repo_url: https://github.com/jdossgollin/dry-guide
theme: "material"

nav:
    - Home: index.md
    - Participation Guide: conduct.md
    - Programs:
        - Bash: bash.md
    - Applications:
        - Reference Manager: zotero.md
    - Group Website: labsite.md
    - Additional Resources: resources.md

markdown_extensions:
    - admonition
    - codehilite
    - smarty
    - meta
    - toc:
        permalink: True
    - attr_list