site_name: Doss-Gollin Group Lab Guide
repo_url: https://github.com/jdossgollin/lab-guide
theme: "material"

nav:
        - Home: index.md
        - Harassment Policy: harassment.md
        - Health and Wellness: health.md
        - New Member Checklist: checklist.md
        - Open Science: open.md
        - Roles and Responsibilities: expectations.md
        - Writing Papers: papers.md

markdown_extensions:
        - admonition
        - attr_list
        - codehilite
        - footnotes
        - meta
        - smarty

plugins:
        - search
