site_name: Doss-Gollin Group Lab Guide
repo_url: https://github.com/jdossgollin/dry-guide
theme: "material"

nav:
    - Home: index.md
    - Code of couduct: conduct.md
    - Health and wellness: health.md
    - Mission statement: mission.md
    - Expectations: expectations.md
    - Infrastructure guide: infrastructure.md
    - Communication: communication.md
    - Coding and software: software.md
    - Writing papers: papers.md

markdown_extensions:
    - admonition
    - attr_list
    - codehilite
    - footnotes
    - meta
    - smarty
    - toc:
        permalink: True