theme:
  name: material
  font:
    text: Roboto
    code: Fira Code
  icon:
    logo: material/account-group-outline
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jdossgollin
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/jdossgollin
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/jamesdossgollin

site_name: Doss-Gollin Group Lab Guide
repo_name: jdossgollin/lab-guide
repo_url: https://github.com/jdossgollin/lab-guide

markdown_extensions:
  - admonition
  - codehilite:
      linenums: true
  - footnotes
  - attr_list
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - search # necessary for search to work
  - awesome-pages
  - git-revision-date-localized:
      type: date
  - pdf-export:
      enabled_if_env: ENABLE_PDF_EXPORT
      combined: true
