site_name: Doss-Gollin Group Lab Guide
repo_name: jdossgollin/lab-guide
repo_url: https://github.com/jdossgollin/lab-guide
theme:
        name: material
        palette:
                scheme: slate
        font:
                text: Roboto
                code: Ubuntu Mono
extra:
        social:
                - icon: fontawesome/brands/github-alt
                  link: https://github.com/squidfunk
                - icon: fontawesome/brands/twitter
                  link: https://twitter.com/squidfunk
                - icon: fontawesome/brands/linkedin
                  link: https://linkedin.com/in/squidfunk

markdown_extensions:
        - admonition
        - codehilite
        - footnotes
        - attr_list

plugins:
        - search # necessary for search to work
        - awesome-pages
        - git-revision-date-localized:
                  type: date
